/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/scan": {
    /** A user (at a GPS location) scans and receives data about nearby resources and interactables */
    post: {
      responses: {
        /** A successful scan */
        200: {
          content: {
            "application/json": components["schemas"]["inline_response_200"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["scan_body"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Coordinate: [number | number, number | number];
    Resource: {
      /** Format: int64 */
      id?: number;
    };
    Region: {
      /** Format: int64 */
      id?: number;
    };
    scan_body: {
      userPosition: components["schemas"]["Coordinate"];
    };
    inline_response_200: {
      resources: components["schemas"]["Resource"][];
      regions: components["schemas"]["Region"][];
      interactableResources: number[];
    };
  };
}

export interface operations {}

export interface external {}
